Make site responsive (Fix #1)
hoppjs/hoppjs.github.io pull request #6
Opened 2017-06-22 19:43 UTC by AtaGowani

# Changes
* Fix terminal
* Add toggler
* License link fixed

Additions and changes made in `index.html` and `style.css`

**Still in progress**

2017-06-23 19:29 UTC, karimsa requested changes

2017-06-23 19:29 UTC, karimsa commented on css/style.css
> +* @file css/index.css
This doesn't match the actual filename.

2017-06-23 19:29 UTC, karimsa commented on css/style.css
> +.navbar-light .navbar-brand, .navbar-light .navbar-brand:hover, .navbar-light .navbar-brand:visited {
CSS selectors should be on separate lines. Fix this manually for now, we'll add linting for styles soon.

2017-06-23 19:29 UTC, karimsa commented on css/style.css
>    background: #fff;
The background is set to white by default.

2017-06-23 20:30 UTC, AtaGowani commented on css/style.css
>    background: #fff;
`.bg-faded` was changing the color to `#f7f7f7`.
I'll get rid of that.

2017-06-23 20:31 UTC, AtaGowani commented on css/style.css
>    background: #fff;
It doesn't seem to have any side effects

2017-06-23 20:37 UTC, karimsa requested changes
Can you upload screenshots of what this looks like on sm, md, and lg?

2017-06-23 20:37 UTC, karimsa commented on css/style.css
> +  padding: 1.5rem 1.5rem;
This can be reduced to `padding: 1.5rem;`

2017-06-26 02:07 UTC, karimsa approved these changes

2017-06-26 02:07 UTC, merged