Improve README (Fix #5)
hoppjs/hoppjs.github.io pull request #8
Opened 2017-06-23 17:40 UTC by AtaGowani

# Changes
`README.md` improved

# Issue
See #5

2017-06-23 19:32 UTC, karimsa requested changes

2017-06-23 19:32 UTC, karimsa commented on README.md
> +# Set up for Contributing
Heading level 1 should only be used once in the entire README.

2017-06-23 19:32 UTC, karimsa commented on README.md
> +This is the repository for the official website for Hopp JS available at [hoppjs.com](http://hoppjs.com).
Keep `hopp` in lowercase at all times, and we'll just call it hopp instead of hoppjs. It's just that `hopp` is taken on Github & as a `.com` domain.

2017-06-23 19:32 UTC, karimsa commented on README.md
> +# Set up for Contributing
For contributing, just say "please make sure you read the contribution guide" (and link to it).

2017-06-23 19:32 UTC, karimsa commented on README.md
> +
* 'LICENSE' section missing.

2017-06-23 19:32 UTC, karimsa commented on README.md
> +**Clone**
Place these steps under their own heading. Maybe something like 'Running locally'

2017-06-26 02:09 UTC, karimsa requested changes

2017-06-26 02:09 UTC, karimsa commented on README.md
> +Please be sure to read the **[Contribution Guide](./.github/CONTRIBUTING.md)** before making any changes. Ready to contribute? Follow the steps below to get started.
Remove the `./`

2017-06-26 02:09 UTC, karimsa commented on README.md
> +
Add a new heading for the setup & add license info at the bottom.

2017-06-28 03:42 UTC, AtaGowani commented on README.md
> +
Not sure if I understand what you mean here.

2017-06-28 03:59 UTC, karimsa approved these changes

2017-06-28 04:00 UTC, karimsa commented
My mistake on the last review.

2017-06-28 04:00 UTC, merged